# Changes here will be overwritten by Copier
_commit: v0.3.3
_src_path: gh:LSSTDESC/RAIL-project-template
author_email: jaime.ruiz-zapatero@ucl.ac.uk
author_name: LSST Dark Energy Science Collaboration (DESC)
create_example_module: true
package_name: rail_prior
project_name: rail-prior
